Closes #11 Create course and associations
idevelopdreams/iscool pull request #21
Opened 2020-02-09 04:59 UTC by landmammal

Creating a Course and associating it to the user who created with a tag of creator
Creating a Course Registration and associating it to the user who registers with a tag of student
Creating a Course Registration and associating it to the course registering with a tag of classes

2020-02-09 22:14 UTC, landmammal commented on models/course.js
> +    User.belongsTo(models.User, {
check out if belongsTo should be Course instead of users

2020-02-09 23:01 UTC, ijust-Frank approved these changes
I Just Frank and I approve this pull request!

2020-02-09 23:06 UTC, ijust-Frank requested changes
Yo had to take back that approval
End points for deleting courses & registrations

2020-02-17 03:17 UTC, ijust-Frank approved these changes

2020-02-17 03:19 UTC, merged